### ISSUE TITLE
Refactorisation des Pipelines CI/CD - Éclatement des Stages

### ISSUE THREAD

**Issue by code-ex0** [EcoWatch0/EcoWatch#97]
## 📋 **Résumé**

Refactoriser les pipelines GitHub Actions actuels pour éclater les stages monolithiques en jobs séparés et optimiser les performances, la lisibilité et la maintenabilité.

## 🎯 **Objectifs**

* **Clarté** : Séparer les responsabilités en jobs distincts
* **Parallélisation** : Exécuter les tâches indépendantes en parallèle
* **Optimisation** : Réduire le temps d'exécution global
* **Maintenabilité** : Faciliter le debug et les modifications
* **Réutilisabilité** : Créer des workflows composables

### Problèmes identifiés :

1. **Pipeline monolithique** : Un seul job `test-and-build` fait tout
2. **Exécution séquentielle** : Pas de parallélisation des tâches indépendantes
3. **Duplication de code** : Variables d'environnement répétées
4. **Temps d'exécution long** : \~15-20 minutes pour un pipeline complet
5. **Difficulté de debug** : Échec d'une étape fait échouer tout le pipeline

### 1\. **Pipeline Principal (**`ci.yml`)

```yaml
jobs:
  setup:           # Cache et dépendances
  lint:            # Linting et formatage
  security:        # Audit de sécurité
  test-unit:       # Tests unitaires
  test-integration: # Tests d'intégration
  build:           # Build des applications
  quality-gate:    # Vérifications qualité
```

### 2\. **Pipeline de Déploiement (**`cd.yml`)

```yaml
jobs:
  build-images:    # Construction des images Docker
  security-scan:   # Scan de sécurité des images
  deploy-staging:  # Déploiement en staging
  e2e-tests:       # Tests end-to-end
  deploy-prod:     # Déploiement en production
```

### 3\. **Workflows Réutilisables**

* `reusable-build.yml` : Build d'une application
* `reusable-test.yml` : Tests d'une application
* `reusable-docker.yml` : Build et push d'une image Docker

### Phase 1 : Restructuration du Pipeline CI

- [ ] **Créer le job** `setup`
  * Installation des dépendances
  * Configuration du cache pnpm
  * Génération du client Prisma
- [ ] **Créer le job** `lint`
  * ESLint sur tous les packages
  * Prettier check
  * TypeScript check
- [ ] **Créer le job** `security`
  * `npm audit` / `pnpm audit`
  * Scan des dépendances vulnérables
  * SAST (Static Application Security Testing)
- [ ] **Séparer les tests par application**
  * `test-api-gateway`
  * `test-web`
  * `test-mqtt-service`
  * `test-data-simulator`
- [ ] **Créer le job** `build`
  * Build en parallèle de toutes les applications
  * Artifacts de build pour les jobs suivants

### Phase 2 : Optimisation du Pipeline Docker

- [ ] **Paralléliser les builds Docker**
  * Un job par image Docker
  * Utilisation de la matrice GitHub Actions
- [ ] **Optimiser les caches Docker**
  * Cache multi-stage
  * Registry cache
- [ ] **Améliorer le scan de sécurité**
  * Scan en parallèle des images
  * Rapports de sécurité détaillés

### Phase 3 : Workflows Réutilisables

- [ ] **Créer** `reusable-app-ci.yml`

  ```yaml
  inputs:
    app-name:
      required: true
      type: string
    node-version:
      default: '20'
      type: string
  ```
- [ ] **Créer** `reusable-docker-build.yml`

  ```yaml
  inputs:
    image-name:
      required: true
      type: string
    dockerfile-target:
      required: true
      type: string
  ```

### Phase 4 : Matrice de Tests

- [ ] **Tests multi-environnements**

  ```yaml
  strategy:
    matrix:
      node-version: [18, 20]
      os: [ubuntu-latest, windows-latest]
  ```
- [ ] **Tests de base de données**

  ```yaml
  strategy:
    matrix:
      postgres-version: [14, 15, 16]
  ```

### 1\. **Parallélisation**

* Tests unitaires en parallèle par application
* Builds Docker simultanés
* Scans de sécurité en parallèle

### 2\. **Cache Intelligent**

* Cache pnpm partagé entre jobs
* Cache Docker layers
* Cache des artifacts de build

### 3\. **Conditions d'Exécution**

* Skip des jobs non nécessaires selon les changements
* Exécution conditionnelle selon les branches

### 4\. **Variables d'Environnement Centralisées**

```yaml
env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'
  POSTGRES_VERSION: '16'
```

## 📈 **Métriques de Succès**

* **Temps d'exécution** : Réduction de 40% (de \~20min à \~12min)
* **Parallélisation** : 70% des jobs exécutés en parallèle
* **Feedback rapide** : Lint et tests unitaires en <5min
* **Taux d'échec** : Réduction des faux positifs de 30%

## 🔍 **Structure des Fichiers Cible**

```
.github/
├── workflows/
│   ├── ci.yml                    # Pipeline principal CI
│   ├── cd.yml                    # Pipeline de déploiement
│   ├── pr-checks.yml            # Vérifications PR
│   └── reusable/
│       ├── app-ci.yml           # CI réutilisable par app
│       ├── docker-build.yml     # Build Docker réutilisable
│       └── security-scan.yml    # Scan de sécurité
└── actions/                     # Actions personnalisées
    ├── setup-node-pnpm/
    └── cache-dependencies/
```

## ⚠️ **Risques et Mitigation**

1. **Complexité accrue** → Documentation détaillée
2. **Temps de migration** → Migration progressive
3. **Dépendances entre jobs** → Définition claire des artifacts

## 🎯 **Critères d'Acceptation**

- [ ] Pipeline CI exécuté en <15 minutes
- [ ] Au moins 3 jobs exécutés en parallèle
- [ ] Workflows réutilisables fonctionnels
- [ ] Documentation mise à jour
- [ ] Tests de régression passés
- [ ] Métriques de performance améliorées
